### ISSUE TITLE
-f reads_fasta flag

### ISSUE THREAD

**Issue by browngcm** [bsipos/uncle_psl#1]
Just looking for clarification on the '-f ' flag. Should these reads be from the target genome or query sequences? What effect does this flag have on the output file?

Any info would be great. Thanks.

**Comment by bsipos** [comment]
The -f flag is to specify the query sequences in fasta format. This should be the same file which was given to blat when aligning. If this flag is specified then the sequence is added to the SAM record (which is missing from the blat output. Hope this helps.

**Comment by browngcm** [comment]
Thanks for the explanation!
