### ISSUE TITLE
Sequence field not found

### ISSUE THREAD

**Issue by GabyBG** [bsipos/uncle_psl#2]
After doing the conversion from PSL to SAM format I noticed that on the output file (SAM) the sequence column is missing...
Do I need to add this column manually? or is there an option that can help with that?  

Also, I am curious about the default settings when we don't use the -N option...

**Comment by bsipos** [comment]
Hi,
Did you provide the reads to the script via the -f option? If yes, then the sequences should be present in the SAM record.
If you do not use the -N option then every large deletion event (potential introns) will be reported as deletions (D cigar operation) and not as introns (N cigar operation).
